# Generated by Django 5.0.7 on 2024-07-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', 'AddSlugToProd'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
