# Generated by Django 5.0.7 on 2024-07-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_address_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
